#!/bin/sh

# Get list of staged go files
STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".go$")

if [ -z "$STAGED_GO_FILES" ]; then
    exit 0
fi

# Format the files
for FILE in $STAGED_GO_FILES; do
    # Run gofmt on the file
    gofmt -w "$FILE"
    # Add the formatted file back to the staging area
    git add "$FILE"
done
