package migration

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// AutoLoadMigrations discovers and returns import paths for all migration packages
// This should be called before InitMigrations()
func AutoLoadMigrations() ([]string, error) {
	// Get current working directory
	cwd, err := os.Getwd()
	if err != nil {
		return nil, err
	}

	// Look for apps directory
	appsDir := filepath.Join(cwd, "apps")
	if _, err := os.Stat(appsDir); os.IsNotExist(err) {
		return nil, nil // No apps directory
	}

	entries, err := os.ReadDir(appsDir)
	if err != nil {
		return nil, err
	}

	var migrationPaths []string
	for _, entry := range entries {
		if entry.IsDir() {
			appName := entry.Name()
			migrationDir := filepath.Join(appsDir, appName, "migrations")

			// Check if migrations directory exists and has .go files
			if hasMigrations(migrationDir) {
				migrationPaths = append(migrationPaths, migrationDir)
			}
		}
	}

	return migrationPaths, nil
}

// hasMigrations checks if directory contains migration files
func hasMigrations(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}

	for _, entry := range entries {
		if !entry.IsDir() && filepath.Ext(entry.Name()) == ".go" {
			name := entry.Name()
			if name != ".gitkeep" && !strings.HasSuffix(name, "_test.go") {
				return true
			}
		}
	}

	return false
}

// GenerateMigrationImports creates a file that imports all migration packages
// Returns the path to the generated file
func GenerateMigrationImports(projectModule string, outputPath string) error {
	// Get current working directory
	cwd, err := os.Getwd()
	if err != nil {
		return err
	}

	// Look for apps directory
	appsDir := filepath.Join(cwd, "apps")
	if _, err := os.Stat(appsDir); os.IsNotExist(err) {
		return nil // No apps directory
	}

	entries, err := os.ReadDir(appsDir)
	if err != nil {
		return err
	}

	var imports []string
	for _, entry := range entries {
		if entry.IsDir() {
			appName := entry.Name()
			migrationDir := filepath.Join(appsDir, appName, "migrations")

			// Check if migrations directory exists and has .go files
			if hasMigrations(migrationDir) {
				importPath := fmt.Sprintf("%s/apps/%s/migrations", projectModule, appName)
				imports = append(imports, importPath)
			}
		}
	}

	if len(imports) == 0 {
		return nil
	}

	// Generate file content
	var sb strings.Builder
	sb.WriteString("// Code generated by Bourbon CLI. DO NOT EDIT.\n")
	sb.WriteString("// This file is auto-generated when running migration commands.\n\n")
	sb.WriteString("package main\n\n")
	sb.WriteString("import (\n")
	for _, imp := range imports {
		sb.WriteString(fmt.Sprintf("\t_ \"%s\"\n", imp))
	}
	sb.WriteString(")\n")

	// Write to file
	return os.WriteFile(outputPath, []byte(sb.String()), 0644)
}
